[tool.briefcase]
# Global defaults for the project (can be overridden by app-specific settings)
briefcase_version = "0.3.15" # Pinned to a potentially more stable version
bundle = "com.example"
project_name = "GuessingGameProject"
version = "0.0.1"

[tool.briefcase.app.guessing_game]
# Basic properties of the application.
formal_name = "Guessing Game"
product_name = "GuessingGame"
bundle = "com.example.guessinggame" # App-specific bundle, overrides global
version = "0.0.1" # App-specific version, overrides global
url = "https://www.example.com/guessing-game"
license.file = "LICENSE" # Points to the LICENSE file
author = "Venkat"
author_email = "venkat.naibhi@gmail.com"
description = "A simple number guessing game for Android."

# 'sources' points directly to your top-level package.
sources = ["guessing_game"]

# The Python version to use for the app.
# Removed specific development version pins for Toga, allowing pip to fetch compatible versions.
requires = [
    "toga-android",
    "toga-core",
]
# IMPORTANT: Simplified main_module and app_module to just "app".
# Briefcase should resolve this based on the 'sources' setting.
main_module = "app"
app_module = "app"

# Android-specific options
[tool.briefcase.app.guessing_game.android]
# The Android API level to target.
target_api = 33 # Or a more recent stable API level
# The minimum Android API level supported.
min_api = 21
# The list of permissions the app requires.
permissions = []
# The list of devices to build for.
device_type = "handset"
# The list of architectures to build for.
supported_abis = ["armeabi-v7a", "arm64-v8a", "x86", "x86_64"]
# The icon for the app (path relative to the project root).
icon = "static/icon.png" # You'll need to create a simple icon.png
